#!/usr/bin/env python3
"""
Score a product idea using the TrendPilot AI opportunity scoring formula.

This script is intentionally dependency-free and uses only Python's standard library.
It does not validate real market demand, sales potential, or profitability.
"""

from __future__ import annotations

import argparse
import csv
import json
from datetime import date
from pathlib import Path

RISK_LEVELS = {"Low", "Medium", "High", "Avoid", "Unknown"}
CONFIDENCE_LEVELS = {"Low", "Medium", "High"}
REVIEW_STATUSES = {"Draft", "Needs Review", "Approved", "Rejected", "Watchlist"}

CSV_COLUMNS = [
    "record_id",
    "product_name",
    "category",
    "region",
    "demand_signal_score",
    "social_visibility_score",
    "price_potential_score",
    "supplier_availability_score",
    "differentiation_potential_score",
    "competition_level_score",
    "shipping_difficulty_score",
    "compliance_risk_score",
    "opportunity_score",
    "evidence_summary",
    "risk_note",
    "risk_level",
    "confidence",
    "next_action",
    "review_status",
    "reviewer_note",
]


def bounded_score(value: int, field_name: str) -> int:
    if value < 1 or value > 5:
        raise argparse.ArgumentTypeError(f"{field_name} must be between 1 and 5.")
    return value


def score_type(field_name: str):
    def parser(value: str) -> int:
        try:
            number = int(value)
        except ValueError as exc:
            raise argparse.ArgumentTypeError(f"{field_name} must be an integer from 1 to 5.") from exc
        return bounded_score(number, field_name)

    return parser


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Score a product idea with the TrendPilot AI scoring model."
    )
    parser.add_argument("--product-name", required=True)
    parser.add_argument("--category", required=True)
    parser.add_argument("--region", default="Global")
    parser.add_argument("--record-id", default=None)

    parser.add_argument("--demand", required=True, type=score_type("demand"))
    parser.add_argument("--social", required=True, type=score_type("social"))
    parser.add_argument("--price", required=True, type=score_type("price"))
    parser.add_argument("--supplier", required=True, type=score_type("supplier"))
    parser.add_argument("--differentiation", required=True, type=score_type("differentiation"))
    parser.add_argument("--competition", required=True, type=score_type("competition"))
    parser.add_argument("--shipping", required=True, type=score_type("shipping"))
    parser.add_argument("--compliance", required=True, type=score_type("compliance"))

    parser.add_argument("--evidence-summary", default="Needs source review before use.")
    parser.add_argument("--risk-note", default="Needs human review before business use.")
    parser.add_argument("--risk-level", default="Unknown", choices=sorted(RISK_LEVELS))
    parser.add_argument("--confidence", default="Low", choices=sorted(CONFIDENCE_LEVELS))
    parser.add_argument("--next-action", default="Validate current sources, competitors, pricing, and compliance requirements.")
    parser.add_argument("--review-status", default="Needs Review", choices=sorted(REVIEW_STATUSES))
    parser.add_argument("--reviewer-note", default="Generated by local scoring example.")
    parser.add_argument(
        "--csv-output",
        default=None,
        help="Optional CSV output path. If the file exists, the row is appended.",
    )
    return parser.parse_args()


def calculate_opportunity_score(args: argparse.Namespace) -> int:
    positive = args.demand + args.social + args.price + args.supplier + args.differentiation
    negative = args.competition + args.shipping + args.compliance
    return positive - negative


def score_interpretation(score: int) -> str:
    if score >= 12:
        return "Strong candidate for deeper research"
    if score >= 8:
        return "Test carefully"
    if score >= 4:
        return "Watchlist"
    return "Avoid unless stronger evidence appears"


def build_record(args: argparse.Namespace) -> dict[str, str | int]:
    opportunity_score = calculate_opportunity_score(args)
    record_id = args.record_id or f"TP-MANUAL-{date.today().strftime('%Y%m%d')}"
    return {
        "record_id": record_id,
        "product_name": args.product_name,
        "category": args.category,
        "region": args.region,
        "demand_signal_score": args.demand,
        "social_visibility_score": args.social,
        "price_potential_score": args.price,
        "supplier_availability_score": args.supplier,
        "differentiation_potential_score": args.differentiation,
        "competition_level_score": args.competition,
        "shipping_difficulty_score": args.shipping,
        "compliance_risk_score": args.compliance,
        "opportunity_score": opportunity_score,
        "score_interpretation": score_interpretation(opportunity_score),
        "evidence_summary": args.evidence_summary,
        "risk_note": args.risk_note,
        "risk_level": args.risk_level,
        "confidence": args.confidence,
        "next_action": args.next_action,
        "review_status": args.review_status,
        "reviewer_note": args.reviewer_note,
    }


def write_csv(record: dict[str, str | int], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    file_exists = output_path.exists()

    with output_path.open("a", encoding="utf-8", newline="") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=CSV_COLUMNS)
        if not file_exists:
            writer.writeheader()
        writer.writerow({column: record.get(column, "") for column in CSV_COLUMNS})


def main() -> None:
    args = parse_args()
    record = build_record(args)

    print(json.dumps(record, indent=2, ensure_ascii=False))
    print()
    print("Reminder: This score is a research signal only. It does not guarantee demand, sales, profit, or product success.")

    if args.csv_output:
        output_path = Path(args.csv_output)
        write_csv(record, output_path)
        print(f"CSV row saved to: {output_path}")


if __name__ == "__main__":
    main()
