#!/usr/bin/env python3
"""Backward-compatible wrapper around the TrendPilot AI CLI score command."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from trendpilot.scoring import build_product_score_record


def score_type(field_name: str):
    def parser(value: str) -> int:
        try:
            number = int(value)
        except ValueError as exc:
            raise argparse.ArgumentTypeError(f"{field_name} must be an integer from 1 to 5.") from exc
        if number < 1 or number > 5:
            raise argparse.ArgumentTypeError(f"{field_name} must be between 1 and 5.")
        return number

    return parser


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Score a product idea with the TrendPilot AI scoring model.")
    parser.add_argument("--product-name", required=True)
    parser.add_argument("--category", required=True)
    parser.add_argument("--region", default="Global")
    parser.add_argument("--record-id", default="TP-MANUAL-001")
    parser.add_argument("--target-audience", default="Not specified")
    parser.add_argument("--demand", required=True, type=score_type("demand"))
    parser.add_argument("--social", required=True, type=score_type("social"))
    parser.add_argument("--price", required=True, type=score_type("price"))
    parser.add_argument("--supplier", required=True, type=score_type("supplier"))
    parser.add_argument("--differentiation", required=True, type=score_type("differentiation"))
    parser.add_argument("--competition", required=True, type=score_type("competition"))
    parser.add_argument("--shipping", required=True, type=score_type("shipping"))
    parser.add_argument("--compliance", required=True, type=score_type("compliance"))
    parser.add_argument("--evidence-summary", default="Needs source review before use.")
    parser.add_argument("--risk-note", default="Needs human review before business use.")
    parser.add_argument("--risk-level", default="Unknown", choices=["Low", "Medium", "High", "Avoid", "Unknown"])
    parser.add_argument("--confidence", default="Low", choices=["Low", "Medium", "High"])
    parser.add_argument("--next-action", default="Validate current sources, competitors, pricing, and compliance requirements.")
    parser.add_argument("--review-status", default="Needs Review", choices=["Draft", "Needs Review", "Approved", "Rejected", "Watchlist"])
    parser.add_argument("--reviewer-note", default="Generated by local scoring example.")
    parser.add_argument("--json-output", default=None, help="Optional JSON output path.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    record = build_product_score_record(
        score_id=args.record_id,
        product_idea=args.product_name,
        category=args.category,
        target_region=args.region,
        target_audience=args.target_audience,
        evidence_summary=args.evidence_summary,
        scores={
            "demand_signal": args.demand,
            "social_visibility": args.social,
            "price_potential": args.price,
            "supplier_availability": args.supplier,
            "differentiation_potential": args.differentiation,
            "competition_level": args.competition,
            "shipping_difficulty": args.shipping,
            "compliance_risk": args.compliance,
        },
        risk_note=args.risk_note,
        risk_level=args.risk_level,
        confidence=args.confidence,
        next_action=args.next_action,
        review_status=args.review_status,
        reviewer_note=args.reviewer_note,
    )
    payload = json.dumps(record, indent=2, ensure_ascii=False)
    print(payload)
    print()
    print("Reminder: This score is a research signal only. It does not guarantee demand, sales, profit, or product success.")
    if args.json_output:
        path = Path(args.json_output)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(payload + "\n", encoding="utf-8")
        print(f"JSON saved to: {path}")


if __name__ == "__main__":
    main()
